version: '3.8'

services:
  closetOrganizer-backend:
    build: 
      context: ./java
      dockerfile: Dockerfile
    container_name: closetOrganizer-backend
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    volumes:
      - ./uploads:/app/uploads

  closetOrganizer-frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: closetOrganizer-frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8081
      - WATCHPACK_POLLING=true
    depends_on:
      - closetOrganizer-backend
