version: '3.8'

services:
  backend:
    build: 
      context: ./java
      dockerfile: Dockerfile
    container_name: closet-organizer-backend
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SERVER_PORT=8081
    volumes:
      - ./uploads:/app/uploads

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: closet-organizer-frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8081
      - WATCHPACK_POLLING=true
    depends_on:
      - backend
